version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+aiomysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/behero
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - .:/app  # 코드 변경사항 실시간 반영
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    depends_on:
      - mysql
    networks:
      - behero-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=behero
    volumes:
      - mysql-dev-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - behero-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  behero-network:
    driver: bridge

volumes:
  mysql-dev-data: