services:
  frontend:
    build: 
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: flutter run -d web-server --web-port 3000 --web-hostname 0.0.0.0

  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080